altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  aa9441af-b25b-49d0-979f-16652b47e50c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-30T21:49:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9e8b4d19-1a13-4742-b0fe-ff5bb1509751
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0fabbdc3-c58c-43bc-a88a-ee441d0e3dce
        userCondition: null
fs: images
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
